blog/urls.py
from django.conf.urls import url, include
from datetime import datetime

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^resources/$', views.guides, name='resources'),
    url(r'^success_blog/$', views.success_blog, name='success_blog'),
    url(r'^signup/$', views.signup, name='apply'),


    # url(r'^(?P<slug>[\w\-]+)/$', views.story),
]

education_haiti/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap


from blog import urls as blog_urls
from people import urls as people_urls
from mentors import urls as our_mentors_urls
from programs import urls as  programs_urls

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from blog import views

from blog.sitemaps import StaticViewSitemap
from mentors.sitemaps import StaticViewSitemap2

sitemaps = {
    'static': StaticViewSitemap,
    'static2': StaticViewSitemap2,
}



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                                content_type='text/plain')),
    url(r'^blog/', include(blog_urls)),
    url(r'^our_mentors/', include(our_mentors_urls)),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
]

if settings.ADMIN_ENABLED:
    urlpatterns.append(url(r'^admin/', admin.site.urls))


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentors/urls.py
from django.conf.urls import url, include
from datetime import datetime

from . import views

urlpatterns = [
    url(r'^$', views.mentors, name='our_mentors'),
    url(r'^mentor_application/$', views.become_a_mentor, name='mentor_application')
]

mentors/models.py
from django.db import models

# Create your models here.

people/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime, timedelta

# Create your models here.

UNIVERSITIES = (
    ('1', 'Illinois State University'),
    ('2', 'Mount Holyoke College'),
    ('3', 'University of Notre Dame'),
    ('4', 'Columbia University'),
    ('5', 'Cornell University'),
    ('6', 'Ecole Polytechnique de Montreal'),
    ('7', 'Georgia Tech University'),
    ('8', 'Harvard University'),
    ('9', 'Louisiana State University'),
    ('10', 'Massachusettes Institute of Technology'),
    ('11', 'McGill University'),
    ('12', 'Moncton University'),
    ('13', 'Southern University'),
    ('14', 'Tufts University'),
    ('15', 'University of Michigan'),
    ('16', 'University of Pennsyvalnia'),
    ('17', 'Cooper Union'),
    ('18', 'St Leo University'),
    ('19', 'Stony Brook University'),
    ('20', 'University of Ottawa'),
    ('21', 'Berea College'),
    ('22', 'Massasoit CC'),
    ('23', 'University of Massachusetts'),
    ('24', 'University of South Florida'),
    ('25', 'Princeton University'),
    ('26', 'Montclair State University'),
    ('27', 'University of Georgia'),
    ('28', 'Slippery Rock University'),
    ('29', 'University of Rochester'),
    ('30', 'TRCC'),
    ('31', 'Syracuse University'),
    ('32', 'University of Virginia'),
    ('33', 'St John\'s University'),
    ('34', 'Wake Forest University'),
    ('35', 'SUNY-ESF'),
    ('36', 'RIT'),
    ('37', 'Manhattan College'),
    ('38', 'American University'),
    ('39', 'N/A'),
    ('40', 'Pace University')
)

# User model
class User(AbstractUser):
    RANK_CHOICES = (
        ('A', 'Mentor'),
        ('B', 'Admin'),
    )

    rank = models.CharField(max_length=255, choices=RANK_CHOICES, default=RANK_CHOICES[1], null=True,)
    undergrad_college = models.CharField(max_length=255, choices=UNIVERSITIES, default='No University')
    hidden = models.BooleanField(default = False)

    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return "%s" % self.email

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def get_university(self):
        "get the mentors university"
        return self.university

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

User._meta.get_field('email')._unique = True


#class Mentee(models.Model):
#    user        = models.OneToOneField(User)
#    picture     = models.ImageField(upload_to="profile_images", blank=True)
#    #graduating = models.DateField() OR highschool = models.CharField(max_lenght=255, choices=HIGHSCHOOLS, required=True)

#    def __str__(self):
#      return "mentee's profile %s" % self.user.email


# Mentor model
class Mentor(models.Model):
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to="mentor_profile_images", blank=True)
#    graduating  = models.DateField()
    undergrad_college = models.CharField(max_length=255, choices=UNIVERSITIES, default='No University', help_text='Your Undergraduate College')
    grad_college = models.CharField(max_length=255, choices=UNIVERSITIES, default='No University', help_text='Your Graduate College')
    majors = models.CharField(max_length=100)
    interests = models.CharField(max_length=150)
    residency = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, default='+(000)0000000')
    current_status = models.CharField(max_length=255)
    school_haiti = models.CharField(max_length=255)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
#   mentees = models.ManyToManyField(Mentee)
#   todos = models.ManyToManyField(ToDo)
    highlight = models.BooleanField(default=False)
    highlight_text = models.TextField(default="Highlight Story")
    hidden = models.BooleanField(default=False)

    REQUIRED_FIELDS = ["university"]

    def __str__(self):
        return "mentor's profile %s" % self.user.email


# To-do App. user is a Mentor, has an emission date, has an expiration date, has a subject.
class ToDo(models.Model):
    author = models.CharField(max_length=25, default='New Author')
    subject = models.CharField(max_length=200)
    emitted = models.DateField(auto_now_add=True)
    expires = models.DateField()
    completion = models.BooleanField(default=False)

    def __str__(self):
        return self.subject + 'by' + self.Mentor.user.name

    def auto_delete_check(self):
        today = datetime.now().date
        expiration_delete = self.expires + timedelta(days=2)
        if today == expiration_delete:
            self.delete()

mentors/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.template import RequestContext
from datetime import datetime
from django.http import HttpRequest
from people.models import Mentor

# Create your views here.

def become_a_mentor(request):
    return render(request, 'mentor_application.html')

def our_mentors(request):
    #Gets the success stories
    mentor = Mentor.objects.all()
    "Renders the our mentors page"
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'mentors.html',
        {'mentors': mentor},
        context_instance=RequestContext(request,
        {
            'title': 'Our Mentors',
            'year': datetime.now().year,
            'date': datetime.now().date(),
        })
    )

def mentors(request):
    mentor = Mentor.objects.all()
    assert isinstance(request, HttpRequest)
    return render(request, 'mentors.html', {'mentors': mentor})

mentors/templates/mentor_application.html
{% extends '../../blog/templates/index.html' %} {% block body %}
<div class="embed-responsive embed-responsive-16by9">
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSceuyATJy7ST9bEHgpJZvG1HuKXhQorYTxd4tNeM8ZZmOGFkQ/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>
{% endblock %}

mentors/templates/mentors.html
{% extends "../../blog/templates/index.html" %} {% block body %}
<div class=highlight-blue>
  <div class=intro>
  <h2 class=text-center> Highlighted Mentor of the Week </h2>
  <style>
    a {
      color: rgb(255,255,0);
    }
  </style>
</div>
{% for mentor in mentors %}
{% if mentor.highlight %}
<div class=jumbotron style=padding:5px>
<div class=media>
{% if mentor.picture %}
<div class=media-left>
<a><img class=media-object src="{{ mentor.picture.url }}"></a>
</div>
{% else %}
<div class=media-left>
<a><img class=media-object alt="Image not available."data-src=holder.js/500x500/auto></a>
</div>
{% endif %}
<div class=media-body>
<h4 class=media-heading style=font-weight:700>{{ mentor.first_name }} {{ mentor.last_name }}</h4>
<h4 class=media-heading>{{ mentor.school_haiti }}</h4>
<h4 class=media-heading>Undergraduate University: {{ mentor.get_undergrad_college_display }}</h4>
{% if mentor.grad_college != '39' %}
<h4 class=media-heading>Graduate University: {{ mentor.get_grad_college_display }}</h4>
{% endif %}
<p style=font-size:18px;> {{ mentor.highlight_text }} </p>
{% endif %}
{% endfor %}
</div></div>
<div class=highlight-blue>
<div class=container>
<div class=intro>
<h3 class=text-center>Mentors</h3>
<style>
  a {
    color: rgb(255,255,0);
  }
</style>
<h4 class=text-center>Education Haiti mentors are young, successful haitien women and men who strive to help their mentees in the process of applying for education abroad. If you are interested in becoming a mentor, please visit <a href="{% url 'mentor_application' %}">this page</a></h4>
</div>

</div>
</div>
{% for mentor in mentors|dictsort:"first_name" %}
<div class=jumbotron style=padding:5px>
<div class=media>
{% if mentor.picture %}
<div class=media-left>
<a><img class=media-object src="{{ mentor.picture.url }}"></a>
</div>
{% else %}
<div class=media-left>
<a><img class=media-object alt="Image not available."data-src=holder.js/500x500/auto></a>
</div>
{% endif %}
<div class=media-body>
<h4 class=media-heading style=font-weight:700>{{ mentor.first_name }} {{ mentor.last_name }}</h4>
<h4 class=media-heading>{{ mentor.school_haiti }}</h4>
<h4 class=media-heading>Undergraduate University: {{ mentor.get_undergrad_college_display }}</h4>
{% if mentor.grad_college != '39' %}
<h4 class=media-heading>Graduate University: {{ mentor.get_grad_college_display }}</h4>
{% endif %}
</div>
</div>
</div>
{% endfor %} {% endblock %}